version: '3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - esdata:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node
        networks:
            - esnetwork
    kibana:
        image: docker.elastic.co/kibana/kibana:6.3.0
        ports:
            - "5601:5601"
        networks:
            - esnetwork
        depends_on:
            - elasticsearch
    redisdb:
        image: redis:6.2-alpine
        restart: always
        networks:
            - esnetwork
        ports:
            - '6379:6379'
        volumes: 
            - cache:/usr/share/redis/data
volumes:
    esdata:
        driver: local
    cache:
        driver: local
networks:
    esnetwork:
        driver: bridge